/*
 * generated by Xtext 2.40.0
 */
package gol.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GDSLUiModule extends AbstractGDSLUiModule {

	public GDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
