/*
 * generated by Xtext 2.40.0
 */
package gol.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import gol.GDSLRuntimeModule;
import gol.GDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GDSLIdeSetup extends GDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GDSLRuntimeModule(), new GDSLIdeModule()));
	}
	
}
