/**
 * generated by Xtext 2.40.0
 */
package gameoflife.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class GDSLIdeModule extends AbstractGDSLIdeModule {
}
