/*
 * generated by Xtext 2.40.0
 */
package gameoflife.ui.tests;

import com.google.inject.Injector;
import gameoflife.ui.internal.GameoflifeActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GameoflifeActivator.getInstance().getInjector("gameoflife.GDSL");
	}

}
