/*
 * generated by Xtext 2.40.0
 */
package gameoflife.serializer;

import com.google.inject.Inject;
import gameoflife.gDSL.Cell;
import gameoflife.gDSL.GDSLPackage;
import gameoflife.gDSL.GOL;
import gameoflife.gDSL.Grid;
import gameoflife.gDSL.Model;
import gameoflife.gDSL.Rule;
import gameoflife.gDSL.Rules;
import gameoflife.services.GDSLGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class GDSLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private GDSLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == GDSLPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case GDSLPackage.CELL:
				sequence_Cell(context, (Cell) semanticObject); 
				return; 
			case GDSLPackage.GOL:
				sequence_GOL(context, (GOL) semanticObject); 
				return; 
			case GDSLPackage.GRID:
				sequence_Grid(context, (Grid) semanticObject); 
				return; 
			case GDSLPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case GDSLPackage.RULE:
				sequence_Rule(context, (Rule) semanticObject); 
				return; 
			case GDSLPackage.RULES:
				sequence_Rules(context, (Rules) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Cell returns Cell
	 *
	 * Constraint:
	 *     (x=INT y=INT)
	 * </pre>
	 */
	protected void sequence_Cell(ISerializationContext context, Cell semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GDSLPackage.Literals.CELL__X) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GDSLPackage.Literals.CELL__X));
			if (transientValues.isValueTransient(semanticObject, GDSLPackage.Literals.CELL__Y) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GDSLPackage.Literals.CELL__Y));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCellAccess().getXINTTerminalRuleCall_1_0(), semanticObject.getX());
		feeder.accept(grammarAccess.getCellAccess().getYINTTerminalRuleCall_3_0(), semanticObject.getY());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     GOL returns GOL
	 *
	 * Constraint:
	 *     (name=ID rules=Rules grid=Grid)
	 * </pre>
	 */
	protected void sequence_GOL(ISerializationContext context, GOL semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GDSLPackage.Literals.GOL__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GDSLPackage.Literals.GOL__NAME));
			if (transientValues.isValueTransient(semanticObject, GDSLPackage.Literals.GOL__RULES) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GDSLPackage.Literals.GOL__RULES));
			if (transientValues.isValueTransient(semanticObject, GDSLPackage.Literals.GOL__GRID) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GDSLPackage.Literals.GOL__GRID));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGOLAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getGOLAccess().getRulesRulesParserRuleCall_2_0(), semanticObject.getRules());
		feeder.accept(grammarAccess.getGOLAccess().getGridGridParserRuleCall_3_0(), semanticObject.getGrid());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Grid returns Grid
	 *
	 * Constraint:
	 *     cell+=Cell+
	 * </pre>
	 */
	protected void sequence_Grid(ISerializationContext context, Grid semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     gol=GOL
	 * </pre>
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GDSLPackage.Literals.MODEL__GOL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GDSLPackage.Literals.MODEL__GOL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getModelAccess().getGolGOLParserRuleCall_0(), semanticObject.getGol());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Rule returns Rule
	 *
	 * Constraint:
	 *     (state=State operator=Compare amount=INT)
	 * </pre>
	 */
	protected void sequence_Rule(ISerializationContext context, Rule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, GDSLPackage.Literals.RULE__STATE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GDSLPackage.Literals.RULE__STATE));
			if (transientValues.isValueTransient(semanticObject, GDSLPackage.Literals.RULE__OPERATOR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GDSLPackage.Literals.RULE__OPERATOR));
			if (transientValues.isValueTransient(semanticObject, GDSLPackage.Literals.RULE__AMOUNT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, GDSLPackage.Literals.RULE__AMOUNT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRuleAccess().getStateStateEnumRuleCall_0_0(), semanticObject.getState());
		feeder.accept(grammarAccess.getRuleAccess().getOperatorCompareEnumRuleCall_3_0(), semanticObject.getOperator());
		feeder.accept(grammarAccess.getRuleAccess().getAmountINTTerminalRuleCall_4_0(), semanticObject.getAmount());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Rules returns Rules
	 *
	 * Constraint:
	 *     rules+=Rule+
	 * </pre>
	 */
	protected void sequence_Rules(ISerializationContext context, Rules semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
