/*
 * generated by Xtext 2.40.0
 */
package gameoflife;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GDSLStandaloneSetup extends GDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new GDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
