/*
 * generated by Xtext 2.40.0
 */
package gameoflife


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GDSLStandaloneSetup extends GDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new GDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
