/*
 * generated by Xtext 2.40.0
 */
package gameoflife.ide

import com.google.inject.Guice
import gameoflife.GDSLRuntimeModule
import gameoflife.GDSLStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class GDSLIdeSetup extends GDSLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new GDSLRuntimeModule, new GDSLIdeModule))
	}
	
}
