/*
 * generated by Xtext 2.40.0
 */
package gameoflife.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGDSLScopeProvider extends DelegatingScopeProvider {
}
