/**
 * generated by Xtext 2.40.0
 */
package gameoflife.gDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Grid</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.gDSL.Grid#getCell <em>Cell</em>}</li>
 * </ul>
 *
 * @see gameoflife.gDSL.GDSLPackage#getGrid()
 * @model
 * @generated
 */
public interface Grid extends EObject
{
  /**
   * Returns the value of the '<em><b>Cell</b></em>' containment reference list.
   * The list contents are of type {@link gameoflife.gDSL.Cell}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell</em>' containment reference list.
   * @see gameoflife.gDSL.GDSLPackage#getGrid_Cell()
   * @model containment="true"
   * @generated
   */
  EList<Cell> getCell();

} // Grid
