/**
 * generated by Xtext 2.40.0
 */
package gameoflife.gDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gameoflife.gDSL.Model#getGol <em>Gol</em>}</li>
 * </ul>
 *
 * @see gameoflife.gDSL.GDSLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Gol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gol</em>' containment reference.
   * @see #setGol(GOL)
   * @see gameoflife.gDSL.GDSLPackage#getModel_Gol()
   * @model containment="true"
   * @generated
   */
  GOL getGol();

  /**
   * Sets the value of the '{@link gameoflife.gDSL.Model#getGol <em>Gol</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gol</em>' containment reference.
   * @see #getGol()
   * @generated
   */
  void setGol(GOL value);

} // Model
