/**
 * generated by Xtext 2.40.0
 */
package persons.tasks.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TaskDSLValidator extends AbstractTaskDSLValidator {
}
