/**
 * generated by Xtext 2.40.0
 */
package gol.gDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see gol.gDSL.GDSLFactory
 * @model kind="package"
 * @generated
 */
public interface GDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.GDSL.gameoflife";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GDSLPackage eINSTANCE = gol.gDSL.impl.GDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link gol.gDSL.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gol.gDSL.impl.ModelImpl
   * @see gol.gDSL.impl.GDSLPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Gol</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GOL = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gol.gDSL.impl.GOLImpl <em>GOL</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gol.gDSL.impl.GOLImpl
   * @see gol.gDSL.impl.GDSLPackageImpl#getGOL()
   * @generated
   */
  int GOL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOL__NAME = 0;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOL__RULES = 1;

  /**
   * The feature id for the '<em><b>Grid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOL__GRID = 2;

  /**
   * The number of structural features of the '<em>GOL</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link gol.gDSL.impl.RulesImpl <em>Rules</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gol.gDSL.impl.RulesImpl
   * @see gol.gDSL.impl.GDSLPackageImpl#getRules()
   * @generated
   */
  int RULES = 2;

  /**
   * The feature id for the '<em><b>Rules</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES__RULES = 0;

  /**
   * The number of structural features of the '<em>Rules</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gol.gDSL.impl.RuleImpl <em>Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gol.gDSL.impl.RuleImpl
   * @see gol.gDSL.impl.GDSLPackageImpl#getRule()
   * @generated
   */
  int RULE = 3;

  /**
   * The feature id for the '<em><b>State</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__STATE = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE__AMOUNT = 2;

  /**
   * The number of structural features of the '<em>Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link gol.gDSL.impl.GridImpl <em>Grid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gol.gDSL.impl.GridImpl
   * @see gol.gDSL.impl.GDSLPackageImpl#getGrid()
   * @generated
   */
  int GRID = 4;

  /**
   * The feature id for the '<em><b>Cell</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID__CELL = 0;

  /**
   * The number of structural features of the '<em>Grid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRID_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link gol.gDSL.impl.CellImpl <em>Cell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gol.gDSL.impl.CellImpl
   * @see gol.gDSL.impl.GDSLPackageImpl#getCell()
   * @generated
   */
  int CELL = 5;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL__Y = 1;

  /**
   * The number of structural features of the '<em>Cell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CELL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link gol.gDSL.State <em>State</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gol.gDSL.State
   * @see gol.gDSL.impl.GDSLPackageImpl#getState()
   * @generated
   */
  int STATE = 6;

  /**
   * The meta object id for the '{@link gol.gDSL.Compare <em>Compare</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see gol.gDSL.Compare
   * @see gol.gDSL.impl.GDSLPackageImpl#getCompare()
   * @generated
   */
  int COMPARE = 7;


  /**
   * Returns the meta object for class '{@link gol.gDSL.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see gol.gDSL.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference '{@link gol.gDSL.Model#getGol <em>Gol</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Gol</em>'.
   * @see gol.gDSL.Model#getGol()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Gol();

  /**
   * Returns the meta object for class '{@link gol.gDSL.GOL <em>GOL</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GOL</em>'.
   * @see gol.gDSL.GOL
   * @generated
   */
  EClass getGOL();

  /**
   * Returns the meta object for the attribute '{@link gol.gDSL.GOL#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see gol.gDSL.GOL#getName()
   * @see #getGOL()
   * @generated
   */
  EAttribute getGOL_Name();

  /**
   * Returns the meta object for the containment reference '{@link gol.gDSL.GOL#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rules</em>'.
   * @see gol.gDSL.GOL#getRules()
   * @see #getGOL()
   * @generated
   */
  EReference getGOL_Rules();

  /**
   * Returns the meta object for the containment reference '{@link gol.gDSL.GOL#getGrid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Grid</em>'.
   * @see gol.gDSL.GOL#getGrid()
   * @see #getGOL()
   * @generated
   */
  EReference getGOL_Grid();

  /**
   * Returns the meta object for class '{@link gol.gDSL.Rules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rules</em>'.
   * @see gol.gDSL.Rules
   * @generated
   */
  EClass getRules();

  /**
   * Returns the meta object for the containment reference list '{@link gol.gDSL.Rules#getRules <em>Rules</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rules</em>'.
   * @see gol.gDSL.Rules#getRules()
   * @see #getRules()
   * @generated
   */
  EReference getRules_Rules();

  /**
   * Returns the meta object for class '{@link gol.gDSL.Rule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule</em>'.
   * @see gol.gDSL.Rule
   * @generated
   */
  EClass getRule();

  /**
   * Returns the meta object for the attribute '{@link gol.gDSL.Rule#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>State</em>'.
   * @see gol.gDSL.Rule#getState()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_State();

  /**
   * Returns the meta object for the attribute '{@link gol.gDSL.Rule#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see gol.gDSL.Rule#getOperator()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Operator();

  /**
   * Returns the meta object for the attribute '{@link gol.gDSL.Rule#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Amount</em>'.
   * @see gol.gDSL.Rule#getAmount()
   * @see #getRule()
   * @generated
   */
  EAttribute getRule_Amount();

  /**
   * Returns the meta object for class '{@link gol.gDSL.Grid <em>Grid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Grid</em>'.
   * @see gol.gDSL.Grid
   * @generated
   */
  EClass getGrid();

  /**
   * Returns the meta object for the containment reference list '{@link gol.gDSL.Grid#getCell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cell</em>'.
   * @see gol.gDSL.Grid#getCell()
   * @see #getGrid()
   * @generated
   */
  EReference getGrid_Cell();

  /**
   * Returns the meta object for class '{@link gol.gDSL.Cell <em>Cell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cell</em>'.
   * @see gol.gDSL.Cell
   * @generated
   */
  EClass getCell();

  /**
   * Returns the meta object for the attribute '{@link gol.gDSL.Cell#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see gol.gDSL.Cell#getX()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_X();

  /**
   * Returns the meta object for the attribute '{@link gol.gDSL.Cell#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see gol.gDSL.Cell#getY()
   * @see #getCell()
   * @generated
   */
  EAttribute getCell_Y();

  /**
   * Returns the meta object for enum '{@link gol.gDSL.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>State</em>'.
   * @see gol.gDSL.State
   * @generated
   */
  EEnum getState();

  /**
   * Returns the meta object for enum '{@link gol.gDSL.Compare <em>Compare</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Compare</em>'.
   * @see gol.gDSL.Compare
   * @generated
   */
  EEnum getCompare();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GDSLFactory getGDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link gol.gDSL.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gol.gDSL.impl.ModelImpl
     * @see gol.gDSL.impl.GDSLPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Gol</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GOL = eINSTANCE.getModel_Gol();

    /**
     * The meta object literal for the '{@link gol.gDSL.impl.GOLImpl <em>GOL</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gol.gDSL.impl.GOLImpl
     * @see gol.gDSL.impl.GDSLPackageImpl#getGOL()
     * @generated
     */
    EClass GOL = eINSTANCE.getGOL();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOL__NAME = eINSTANCE.getGOL_Name();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOL__RULES = eINSTANCE.getGOL_Rules();

    /**
     * The meta object literal for the '<em><b>Grid</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GOL__GRID = eINSTANCE.getGOL_Grid();

    /**
     * The meta object literal for the '{@link gol.gDSL.impl.RulesImpl <em>Rules</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gol.gDSL.impl.RulesImpl
     * @see gol.gDSL.impl.GDSLPackageImpl#getRules()
     * @generated
     */
    EClass RULES = eINSTANCE.getRules();

    /**
     * The meta object literal for the '<em><b>Rules</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RULES__RULES = eINSTANCE.getRules_Rules();

    /**
     * The meta object literal for the '{@link gol.gDSL.impl.RuleImpl <em>Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gol.gDSL.impl.RuleImpl
     * @see gol.gDSL.impl.GDSLPackageImpl#getRule()
     * @generated
     */
    EClass RULE = eINSTANCE.getRule();

    /**
     * The meta object literal for the '<em><b>State</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__STATE = eINSTANCE.getRule_State();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__OPERATOR = eINSTANCE.getRule_Operator();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RULE__AMOUNT = eINSTANCE.getRule_Amount();

    /**
     * The meta object literal for the '{@link gol.gDSL.impl.GridImpl <em>Grid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gol.gDSL.impl.GridImpl
     * @see gol.gDSL.impl.GDSLPackageImpl#getGrid()
     * @generated
     */
    EClass GRID = eINSTANCE.getGrid();

    /**
     * The meta object literal for the '<em><b>Cell</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRID__CELL = eINSTANCE.getGrid_Cell();

    /**
     * The meta object literal for the '{@link gol.gDSL.impl.CellImpl <em>Cell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gol.gDSL.impl.CellImpl
     * @see gol.gDSL.impl.GDSLPackageImpl#getCell()
     * @generated
     */
    EClass CELL = eINSTANCE.getCell();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__X = eINSTANCE.getCell_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CELL__Y = eINSTANCE.getCell_Y();

    /**
     * The meta object literal for the '{@link gol.gDSL.State <em>State</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gol.gDSL.State
     * @see gol.gDSL.impl.GDSLPackageImpl#getState()
     * @generated
     */
    EEnum STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '{@link gol.gDSL.Compare <em>Compare</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see gol.gDSL.Compare
     * @see gol.gDSL.impl.GDSLPackageImpl#getCompare()
     * @generated
     */
    EEnum COMPARE = eINSTANCE.getCompare();

  }

} //GDSLPackage
