/**
 * generated by Xtext 2.40.0
 */
package gol.gDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>GOL</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gol.gDSL.GOL#getName <em>Name</em>}</li>
 *   <li>{@link gol.gDSL.GOL#getRules <em>Rules</em>}</li>
 *   <li>{@link gol.gDSL.GOL#getGrid <em>Grid</em>}</li>
 * </ul>
 *
 * @see gol.gDSL.GDSLPackage#getGOL()
 * @model
 * @generated
 */
public interface GOL extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see gol.gDSL.GDSLPackage#getGOL_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link gol.gDSL.GOL#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Rules</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' containment reference.
   * @see #setRules(Rules)
   * @see gol.gDSL.GDSLPackage#getGOL_Rules()
   * @model containment="true"
   * @generated
   */
  Rules getRules();

  /**
   * Sets the value of the '{@link gol.gDSL.GOL#getRules <em>Rules</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rules</em>' containment reference.
   * @see #getRules()
   * @generated
   */
  void setRules(Rules value);

  /**
   * Returns the value of the '<em><b>Grid</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Grid</em>' containment reference.
   * @see #setGrid(Grid)
   * @see gol.gDSL.GDSLPackage#getGOL_Grid()
   * @model containment="true"
   * @generated
   */
  Grid getGrid();

  /**
   * Sets the value of the '{@link gol.gDSL.GOL#getGrid <em>Grid</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Grid</em>' containment reference.
   * @see #getGrid()
   * @generated
   */
  void setGrid(Grid value);

} // GOL
