/**
 * generated by Xtext 2.40.0
 */
package gol.gDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link gol.gDSL.Rule#getState <em>State</em>}</li>
 *   <li>{@link gol.gDSL.Rule#getOperator <em>Operator</em>}</li>
 *   <li>{@link gol.gDSL.Rule#getAmount <em>Amount</em>}</li>
 * </ul>
 *
 * @see gol.gDSL.GDSLPackage#getRule()
 * @model
 * @generated
 */
public interface Rule extends EObject
{
  /**
   * Returns the value of the '<em><b>State</b></em>' attribute.
   * The literals are from the enumeration {@link gol.gDSL.State}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>State</em>' attribute.
   * @see gol.gDSL.State
   * @see #setState(State)
   * @see gol.gDSL.GDSLPackage#getRule_State()
   * @model
   * @generated
   */
  State getState();

  /**
   * Sets the value of the '{@link gol.gDSL.Rule#getState <em>State</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State</em>' attribute.
   * @see gol.gDSL.State
   * @see #getState()
   * @generated
   */
  void setState(State value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link gol.gDSL.Compare}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see gol.gDSL.Compare
   * @see #setOperator(Compare)
   * @see gol.gDSL.GDSLPackage#getRule_Operator()
   * @model
   * @generated
   */
  Compare getOperator();

  /**
   * Sets the value of the '{@link gol.gDSL.Rule#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see gol.gDSL.Compare
   * @see #getOperator()
   * @generated
   */
  void setOperator(Compare value);

  /**
   * Returns the value of the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount</em>' attribute.
   * @see #setAmount(int)
   * @see gol.gDSL.GDSLPackage#getRule_Amount()
   * @model
   * @generated
   */
  int getAmount();

  /**
   * Sets the value of the '{@link gol.gDSL.Rule#getAmount <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount</em>' attribute.
   * @see #getAmount()
   * @generated
   */
  void setAmount(int value);

} // Rule
