/**
 * generated by Xtext 2.40.0
 */
package gol.gDSL;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>State</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see gol.gDSL.GDSLPackage#getState()
 * @model
 * @generated
 */
public enum State implements Enumerator
{
  /**
   * The '<em><b>Live</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIVE_VALUE
   * @generated
   * @ordered
   */
  LIVE(0, "Live", "Live"),

  /**
   * The '<em><b>Dead</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEAD_VALUE
   * @generated
   * @ordered
   */
  DEAD(1, "Dead", "Dead"),

  /**
   * The '<em><b>Die</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DIE_VALUE
   * @generated
   * @ordered
   */
  DIE(2, "Die", "Die"),

  /**
   * The '<em><b>To Alive</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TO_ALIVE_VALUE
   * @generated
   * @ordered
   */
  TO_ALIVE(3, "ToAlive", "ToAlive");

  /**
   * The '<em><b>Live</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIVE
   * @model name="Live"
   * @generated
   * @ordered
   */
  public static final int LIVE_VALUE = 0;

  /**
   * The '<em><b>Dead</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DEAD
   * @model name="Dead"
   * @generated
   * @ordered
   */
  public static final int DEAD_VALUE = 1;

  /**
   * The '<em><b>Die</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DIE
   * @model name="Die"
   * @generated
   * @ordered
   */
  public static final int DIE_VALUE = 2;

  /**
   * The '<em><b>To Alive</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TO_ALIVE
   * @model name="ToAlive"
   * @generated
   * @ordered
   */
  public static final int TO_ALIVE_VALUE = 3;

  /**
   * An array of all the '<em><b>State</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final State[] VALUES_ARRAY =
    new State[]
    {
      LIVE,
      DEAD,
      DIE,
      TO_ALIVE,
    };

  /**
   * A public read-only list of all the '<em><b>State</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<State> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>State</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static State get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      State result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>State</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static State getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      State result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>State</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static State get(int value)
  {
    switch (value)
    {
      case LIVE_VALUE: return LIVE;
      case DEAD_VALUE: return DEAD;
      case DIE_VALUE: return DIE;
      case TO_ALIVE_VALUE: return TO_ALIVE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private State(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //State
