/**
 * generated by Xtext 2.40.0
 */
package gameoflife.ui.contentassist;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GDSLProposalProvider extends AbstractGDSLProposalProvider {
}
