/**
 * generated by Xtext 2.40.0
 */
package persons.tasks.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TaskDSLIdeModule extends AbstractTaskDSLIdeModule {
}
