/*
 * generated by Xtext 2.40.0
 */
package gameoflife.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class GDSLUiModule extends AbstractGDSLUiModule {
}
