/*
 * generated by Xtext 2.40.0
 */
package persons.tasks


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TaskDSLStandaloneSetup extends TaskDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new TaskDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
