/*
 * generated by Xtext 2.40.0
 */
package gameoflife.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import gameoflife.ide.contentassist.antlr.internal.InternalGDSLParser;
import gameoflife.services.GDSLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class GDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(GDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, GDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStateAccess().getAlternatives(), "rule__State__Alternatives");
			builder.put(grammarAccess.getCompareAccess().getAlternatives(), "rule__Compare__Alternatives");
			builder.put(grammarAccess.getGOLAccess().getGroup(), "rule__GOL__Group__0");
			builder.put(grammarAccess.getRulesAccess().getGroup(), "rule__Rules__Group__0");
			builder.put(grammarAccess.getRuleAccess().getGroup(), "rule__Rule__Group__0");
			builder.put(grammarAccess.getGridAccess().getGroup(), "rule__Grid__Group__0");
			builder.put(grammarAccess.getCellAccess().getGroup(), "rule__Cell__Group__0");
			builder.put(grammarAccess.getModelAccess().getGolAssignment(), "rule__Model__GolAssignment");
			builder.put(grammarAccess.getGOLAccess().getNameAssignment_1(), "rule__GOL__NameAssignment_1");
			builder.put(grammarAccess.getGOLAccess().getRulesAssignment_2(), "rule__GOL__RulesAssignment_2");
			builder.put(grammarAccess.getGOLAccess().getGridAssignment_3(), "rule__GOL__GridAssignment_3");
			builder.put(grammarAccess.getRulesAccess().getRulesAssignment_2(), "rule__Rules__RulesAssignment_2");
			builder.put(grammarAccess.getRuleAccess().getStateAssignment_0(), "rule__Rule__StateAssignment_0");
			builder.put(grammarAccess.getRuleAccess().getOperatorAssignment_3(), "rule__Rule__OperatorAssignment_3");
			builder.put(grammarAccess.getRuleAccess().getAmountAssignment_4(), "rule__Rule__AmountAssignment_4");
			builder.put(grammarAccess.getGridAccess().getCellAssignment_2(), "rule__Grid__CellAssignment_2");
			builder.put(grammarAccess.getCellAccess().getXAssignment_1(), "rule__Cell__XAssignment_1");
			builder.put(grammarAccess.getCellAccess().getYAssignment_3(), "rule__Cell__YAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private GDSLGrammarAccess grammarAccess;

	@Override
	protected InternalGDSLParser createParser() {
		InternalGDSLParser result = new InternalGDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public GDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
